$('.slider-principal').slick({
dots:true,
infinite:true,
speed:300,
slidesToShow:1,
adaptiveHeight:true,
autoplay:true,
autoplaySpeed:2000
});
$('.slider-parceiros').slick({
    dots:true,
    infinite:true,
    speed:300,
    slidesToShow:1,
    adaptiveHeight:true,
    autoplay:true,
    autoplaySpeed:2000
    });
    $('.slider-sobrenos').slick({
        dots:true,
        infinite:true,
        speed:300,
        slidesToShow:1,
        adaptiveHeight:true,
        autoplay:true,
        autoplaySpeed:2000
        });